[features]
seeds = false
skip-lint = false
[programs.devnet]
token_presale = "71L39GCzAeMkUted5KscB2e1oEuf7ZKdVAVaDgRmZ3VL"

[programs.localnet]
token_presale = "71L39GCzAeMkUted5KscB2e1oEuf7ZKdVAVaDgRmZ3VL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/hieudo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
